### ISSUE TITLE
Rotation of published video is always portrait while in background

### ISSUE THREAD

**Issue by bennnjamin** [livekit/client-sdk-android#535] opened 2024-11-08 15:22 UTC
**Describe the bug**
When testing out the sample apps, you can rotate the device to switch between publishing landscape and portrait video. If you bind the Camera to a service lifecycle so that you can publish video in the call while in the background then upon pressing the home button the video will revert back to portrait.

**To Reproduce**
1. Enable background video publishing using a Foreground Service
2. Publish video to a room
3. Rotate device to landscape to publish landscape video
4. Press home button
5. Video reverts back to portrait

**Expected behavior**
The video rotation should match the device, or the SDK should expose APIs so the developer can manage video rotation.

**Device Info:**
 - Device: Samsung S22
 - OS: Android 14
 - LiveKit SDK version: 2.10.0

**Additional context**
- I've tried forcing the app to only run in landscape but that doesn't fix the issue
- I've tried both with and without CameraX helper
- I have looked for methods in the SDK to control rotation manually and haven't found any

**Comment by bennnjamin** [comment] 2024-11-12 22:48
I have found that the issue is this method in the WebRTC fork https://github.com/webrtc-sdk/webrtc/blob/543121ba1cd47780e92d48546b880333265b37b5/sdk/android/src/java/org/webrtc/CameraSession.java#L42

I can close and re-open this issue there but it is also possible to workaround the issue in this repo in the `getFrameOrientation` method of `CameraXSession`.

**Comment by davidliu** [comment] 2024-11-13 02:42
Tried it myself, and it seems to follow the orientation of the device's UI rotation (which may not physically line up with actual rotation). That is, since the home launcher doesn't support landscape (on my device at least), it forces the UI rotation to portrait and the camera follows that. If you go into a separate app that does support landscape, the camera will correctly reorient to landscape as well.

Closing as intended behavior, since users aren't likely to stay in the landscape physical rotation when entering a portrait only app.

**Closed by davidliu** 2024-11-13 02:42 UTC
Labels: bug
